
import React from 'react';
import { Item, ItemMode, ItemStatus, User, KindStory } from './types';

export const AREAS = ['Johar Town', 'DHA', 'Model Town', 'Gulberg', 'Wapda Town'];

export const COLORS = {
  kindness: '#065f46', // Deep Emerald
  warm: '#fff7ed',     // Warm Sand
  softBg: '#fffaf5',   // Cream
  accent: '#f59e0b',   // Saffron
};

export const DUMMY_USERS: User[] = [
  {
    id: 'u1',
    name: 'Khalid Karim',
    avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&q=80&w=400',
    bio: 'Proud resident of Lahore. I believe in circular economy and helping neighbors.',
    area: 'DHA Phase 5',
    accountAge: '2 years',
    kindnessScore: 98,
    successfulExchanges: 45,
    verified: true,
  },
  {
    id: 'u2',
    name: 'Ali Raza',
    avatar: 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?auto=format&fit=crop&q=80&w=400',
    bio: 'Frequent swapper in Johar Town. Tech enthusiast.',
    area: 'Johar Town',
    accountAge: '1 year',
    kindnessScore: 85,
    successfulExchanges: 12,
    verified: true,
  },
  {
    id: 'u3',
    name: 'Fatima Zahra',
    avatar: 'https://images.unsplash.com/photo-1567532939604-b6b5b0db2604?auto=format&fit=crop&q=80&w=400',
    bio: 'Teacher and avid reader. I love sharing knowledge and books.',
    area: 'Gulberg III',
    accountAge: '3 years',
    kindnessScore: 100,
    successfulExchanges: 89,
    verified: true,
  }
];

export const DUMMY_ITEMS: Item[] = [
  {
    id: 'i1',
    title: 'Calculus: Early Transcendentals',
    description: 'Perfect condition textbook. Used for one semester at LUMS. Giving away for free to any student who needs it for their degree.',
    category: 'Books',
    condition: 'Like New',
    mode: ItemMode.FREE,
    status: ItemStatus.AVAILABLE,
    images: ['https://images.unsplash.com/photo-1543004218-ee141104e6c3?auto=format&fit=crop&q=80&w=800'],
    owner: DUMMY_USERS[2],
    area: 'Gulberg',
    createdAt: '2 hours ago',
  },
  {
    id: 'i2',
    title: 'Wooden Building Blocks Set',
    description: 'Classic wooden blocks for children. Safe, paint-free, and great for creativity. My kids have outgrown them.',
    category: 'Toys',
    condition: 'Gently Used',
    mode: ItemMode.BARTER,
    barterFor: 'Storybooks or puzzles',
    status: ItemStatus.AVAILABLE,
    images: ['https://images.unsplash.com/photo-1618842676088-c4d48a6a7c9d?auto=format&fit=crop&q=80&w=800'],
    owner: DUMMY_USERS[0],
    area: 'DHA',
    createdAt: '5 hours ago',
  },
  {
    id: 'i3',
    title: 'Electric Hand Mixer (7-Speed)',
    description: 'Fully functional hand mixer, used for occasional baking. Comes with all attachments. Selling at a low price as I upgraded.',
    category: 'Electronics',
    condition: 'Functional',
    mode: ItemMode.LOW_PRICE,
    price: 1500,
    status: ItemStatus.AVAILABLE,
    images: ['https://images.unsplash.com/photo-1590186870716-2fd2487fd5f8?auto=format&fit=crop&q=80&w=800'],
    owner: DUMMY_USERS[1],
    area: 'Johar Town',
    createdAt: '1 day ago',
  },
  {
    id: 'i4',
    title: 'Cotton Embroidered Kurta',
    description: 'Beautiful navy blue cotton kurta with light white embroidery. Size Medium. Only worn on Eid once. Like brand new.',
    category: 'Clothes',
    condition: 'Like New',
    mode: ItemMode.FREE,
    status: ItemStatus.AVAILABLE,
    images: ['https://images.unsplash.com/photo-1610030469983-98e550d6193c?auto=format&fit=crop&q=80&w=800'],
    owner: DUMMY_USERS[0],
    area: 'DHA',
    createdAt: '3 days ago',
  },
  {
    id: 'i5',
    title: 'Wireless Keyboard & Mouse',
    description: 'Logitech wireless combo. Works perfectly, just needs new batteries. Great for home office setups.',
    category: 'Electronics',
    condition: 'Gently Used',
    mode: ItemMode.BARTER,
    barterFor: 'Desk lamp or plant',
    status: ItemStatus.AVAILABLE,
    images: ['https://images.unsplash.com/photo-1511467687858-23d96c32e4ae?auto=format&fit=crop&q=80&w=800'],
    owner: DUMMY_USERS[1],
    area: 'Wapda Town',
    createdAt: '4 hours ago',
  },
  {
    id: 'i6',
    title: 'Set of 4 Ceramic Coffee Mugs',
    description: 'Stylish matte finish mugs. Minimalist design. No chips or cracks. We have too many in the kitchen cupboard.',
    category: 'Household',
    condition: 'Excellent',
    mode: ItemMode.LOW_PRICE,
    price: 800,
    status: ItemStatus.AVAILABLE,
    images: ['https://images.unsplash.com/photo-1514228742587-6b1558fcca3d?auto=format&fit=crop&q=80&w=800'],
    owner: DUMMY_USERS[2],
    area: 'Model Town',
    createdAt: '12 hours ago',
  },
  {
    id: 'i7',
    title: 'Air Fryer (4.2L)',
    description: 'Hardly used air fryer. Makes great snacks with less oil. Moving away so selling at a very kind price.',
    category: 'Electronics',
    condition: 'Excellent',
    mode: ItemMode.LOW_PRICE,
    price: 4500,
    status: ItemStatus.AVAILABLE,
    images: ['https://images.unsplash.com/photo-1584269600464-37b1b58a9fe7?auto=format&fit=crop&q=80&w=800'],
    owner: DUMMY_USERS[1],
    area: 'Gulberg',
    createdAt: '1 hour ago',
  },
  {
    id: 'i8',
    title: 'Monopoly Board Game',
    description: 'Classic Monopoly. All pieces and cards are present. Great for family nights.',
    category: 'Toys',
    condition: 'Gently Used',
    mode: ItemMode.BARTER,
    barterFor: 'Scrabble or Ludo',
    status: ItemStatus.AVAILABLE,
    images: ['https://images.unsplash.com/photo-1589805483315-77b5be49c00b?auto=format&fit=crop&q=80&w=800'],
    owner: DUMMY_USERS[0],
    area: 'DHA',
    createdAt: '6 hours ago',
  },
  {
    id: 'i9',
    title: 'Snake Plant (Indoor)',
    description: 'Low maintenance indoor plant. Great for air purification. Giving it away for free to a plant lover!',
    category: 'Household',
    condition: 'Healthy',
    mode: ItemMode.FREE,
    status: ItemStatus.AVAILABLE,
    images: ['https://images.unsplash.com/photo-1596547609652-9cf5d8d76921?auto=format&fit=crop&q=80&w=800'],
    owner: DUMMY_USERS[2],
    area: 'Model Town',
    createdAt: '30 mins ago',
  },
  {
    id: 'i10',
    title: 'Digital DSLR Camera',
    description: 'Canon EOS series. Older model but takes beautiful photos. Perfect for a beginner hobbyist.',
    category: 'Electronics',
    condition: 'Gently Used',
    mode: ItemMode.BARTER,
    barterFor: 'Tablet or Laptop',
    status: ItemStatus.AVAILABLE,
    images: ['https://images.unsplash.com/photo-1516035069371-29a1b244cc32?auto=format&fit=crop&q=80&w=800'],
    owner: DUMMY_USERS[1],
    area: 'Johar Town',
    createdAt: '8 hours ago',
  },
  {
    id: 'i11',
    title: 'Designer Silk Scarf',
    description: '100% pure silk. Vibrant colors. Never worn, was a gift.',
    category: 'Clothes',
    condition: 'Brand New',
    mode: ItemMode.LOW_PRICE,
    price: 2200,
    status: ItemStatus.AVAILABLE,
    images: ['https://images.unsplash.com/photo-1601924994987-69e26d50dc26?auto=format&fit=crop&q=80&w=800'],
    owner: DUMMY_USERS[0],
    area: 'DHA',
    createdAt: '2 days ago',
  },
  {
    id: 'i12',
    title: 'Science Fiction Novel Set',
    description: 'Collection of 5 classic sci-fi books. If you love space and aliens, these are for you!',
    category: 'Books',
    condition: 'Excellent',
    mode: ItemMode.BARTER,
    barterFor: 'History books',
    status: ItemStatus.AVAILABLE,
    images: ['https://images.unsplash.com/photo-1516979187457-637abb4f9353?auto=format&fit=crop&q=80&w=800'],
    owner: DUMMY_USERS[2],
    area: 'Gulberg',
    createdAt: '1 day ago',
  }
];

export const DUMMY_STORIES: KindStory[] = [
  {
    id: 's1',
    userId: 'u1',
    userName: 'Khalid Karim',
    userAvatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&q=80&w=400',
    content: "Yesterday I gave my old sewing machine to a young girl in Model Town who wanted to start her own small business. The smile on her face made my month!",
    image: 'https://images.unsplash.com/photo-1517502474097-f9b30659dadb?auto=format&fit=crop&q=80&w=600',
    appreciations: 124,
  },
  {
    id: 's2',
    userId: 'u3',
    userName: 'Fatima Zahra',
    userAvatar: 'https://images.unsplash.com/photo-1567532939604-b6b5b0db2604?auto=format&fit=crop&q=80&w=400',
    content: "Someone from Gulberg swapped their gardening tools for my old novels. We ended up sharing a cup of chai and some great stories. This community is amazing.",
    appreciations: 89,
  }
];
